
import java.awt.Component;
import java.io.File;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author elisc
 */
public class VelocityGUI extends javax.swing.JFrame {

    private VelocityTableModel model = new VelocityTableModel();
    private VelocityDialog dlg = new VelocityDialog(this, true);
    private File f = new File("./data.bin");

    /**
     * Creates new form GUI
     */
    public VelocityGUI() {
        initComponents();
        this.tableOut.setModel(model);
        tableOut.setDefaultRenderer(Object.class, new VelocityTableCellRenderer());
        model.add(new Measurement(LocalDateTime.now(), "TEST", 0, 0.0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mMain = new javax.swing.JMenu();
        mAdd = new javax.swing.JMenuItem();
        mDelete = new javax.swing.JMenuItem();
        mAvg = new javax.swing.JMenuItem();
        mLoad = new javax.swing.JMenuItem();
        mSave = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOut = new javax.swing.JTable();

        mMain.setText("Menu");

        mAdd.setText("Hinzufügen");
        mAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAddActionPerformed(evt);
            }
        });
        mMain.add(mAdd);

        mDelete.setText("Löschen");
        mDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mDeleteActionPerformed(evt);
            }
        });
        mMain.add(mDelete);

        mAvg.setText("Durchschnitt");
        mAvg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAvgActionPerformed(evt);
            }
        });
        mMain.add(mAvg);

        mLoad.setText("Laden");
        mLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLoadActionPerformed(evt);
            }
        });
        mMain.add(mLoad);

        mSave.setText("Speichern");
        mSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSaveActionPerformed(evt);
            }
        });
        mMain.add(mSave);

        jPopupMenu1.add(mMain);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableOut.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableOut.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tableOut);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAddActionPerformed
        dlg.setVisible(true);
        if (dlg.IsOK()) {
            Measurement m = dlg.getMeasurement();
            model.add(m);
        }
    }//GEN-LAST:event_mAddActionPerformed

    private void mDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mDeleteActionPerformed
        model.delete(tableOut.getSelectedRows());
    }//GEN-LAST:event_mDeleteActionPerformed

    private void mAvgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAvgActionPerformed
        JOptionPane.showMessageDialog(null, model.averageViolation());
    }//GEN-LAST:event_mAvgActionPerformed

    private void mSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSaveActionPerformed
        try {
            model.save(f);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_mSaveActionPerformed

    private void mLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLoadActionPerformed
        try {
            model.load(f);
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_mLoadActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VelocityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VelocityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VelocityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VelocityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VelocityGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mAdd;
    private javax.swing.JMenuItem mAvg;
    private javax.swing.JMenuItem mDelete;
    private javax.swing.JMenuItem mLoad;
    private javax.swing.JMenu mMain;
    private javax.swing.JMenuItem mSave;
    private javax.swing.JTable tableOut;
    // End of variables declaration//GEN-END:variables
}
