
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ASUS
 */
public class VelocityDialog extends javax.swing.JDialog {

    public boolean IsOK() {
        return isOK;
    }

    public VelocityDialog() {

    }

    /*public void sendChangeDate(Appointment ap){
        LocalDateTime datetime = ap.getDatum();
        tfDay.setText("" + datetime.getDayOfMonth());
        tfMonth.setText("" + datetime.getMonthValue());
        tfYear.setText("" + datetime.getYear());
        tfHour.setText("" + datetime.getHour());
        tfMinute.setText("" + datetime.getMinute());
        tfText.setText(ap.getText());
    }*/
    
    public Measurement getMeasurement() {
        return m;
    }
    boolean isOK = true;
    Measurement m = null;

    /**
     * Creates new form AppointmentDialog
     */
    public VelocityDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tfDatum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfUhrzeit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfKennzeichen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfGemessen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfErlaubt = new javax.swing.JTextField();
        btÜbernehmen = new javax.swing.JButton();
        btAbbrechen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Termin-Eingabe");
        getContentPane().setLayout(new java.awt.GridLayout(6, 2));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Datum:");
        getContentPane().add(jLabel2);

        tfDatum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDatum.setText("08.10.2013");
        tfDatum.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.pink));
        getContentPane().add(tfDatum);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Uhrzeit:");
        getContentPane().add(jLabel3);

        tfUhrzeit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfUhrzeit.setText("07:55");
        tfUhrzeit.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.pink));
        tfUhrzeit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUhrzeitActionPerformed(evt);
            }
        });
        getContentPane().add(tfUhrzeit);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Kennzeichen:");
        getContentPane().add(jLabel4);

        tfKennzeichen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfKennzeichen.setText("GU-RASER1");
        tfKennzeichen.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.pink));
        getContentPane().add(tfKennzeichen);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("V-Gemessen:");
        getContentPane().add(jLabel5);

        tfGemessen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfGemessen.setText("123");
        tfGemessen.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.pink));
        getContentPane().add(tfGemessen);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("V-Erlaubt:");
        getContentPane().add(jLabel6);

        tfErlaubt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfErlaubt.setText("80");
        tfErlaubt.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.pink));
        getContentPane().add(tfErlaubt);

        btÜbernehmen.setText("Übernehmen");
        btÜbernehmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btÜbernehmenActionPerformed(evt);
            }
        });
        getContentPane().add(btÜbernehmen);

        btAbbrechen.setText("Abbrechen");
        btAbbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbbrechenActionPerformed(evt);
            }
        });
        getContentPane().add(btAbbrechen);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btÜbernehmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btÜbernehmenActionPerformed
        try {
            LocalDateTime datum
                    = LocalDateTime.parse(tfDatum.getText() + " " + tfUhrzeit.getText(),
                            DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm"));
            String kennzeichen = tfKennzeichen.getText();
            int erlaubt = Integer.parseInt(tfErlaubt.getText());
            double gemessen = Double.parseDouble(tfGemessen.getText());
            this.dispose();
            m = new Measurement(datum, kennzeichen, erlaubt, gemessen);
            isOK = true;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Falsche Eingabeparameter!");
        }
        
    }//GEN-LAST:event_btÜbernehmenActionPerformed

    private void btAbbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbbrechenActionPerformed
        this.dispose();
        isOK = false;
    }//GEN-LAST:event_btAbbrechenActionPerformed

    private void tfUhrzeitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUhrzeitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUhrzeitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VelocityDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VelocityDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VelocityDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VelocityDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VelocityDialog dialog = new VelocityDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbbrechen;
    private javax.swing.JButton btÜbernehmen;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tfDatum;
    private javax.swing.JTextField tfErlaubt;
    private javax.swing.JTextField tfGemessen;
    private javax.swing.JTextField tfKennzeichen;
    private javax.swing.JTextField tfUhrzeit;
    // End of variables declaration//GEN-END:variables
}
